# use this workflow as an example for Lab 2 if you are stuck / need inspiration
name: Node.js CI

on:
  push:

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    permissions:
      write-all # needed for the test reporter check

    steps:
    - uses: actions/checkout@v3

    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure() # run this step even if previous step failed
      with:
        name: "Mocha Tests ${{ matrix.node-version }}" # Name of the check run which will be created
        path: test-results.json # Path to test results
        reporter: mocha-json    # Format of test results